//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QLSieuThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
       
        public HangHoa()
        {

        }

        public HangHoa(string maHH, string tenHang, string maNH, string xuatXu, int giaNhap, int giaBan, string donViTinh, string nhaCungCap, string maVach, int dinhMuc, int soLuong, bool trangThaiBan, int vAT)
        {
            MaHH = maHH;
            TenHang = tenHang;
            MaNH = maNH;
            XuatXu = xuatXu;
            GiaNhap = giaNhap;
            GiaBan = giaBan;
            DonViTinh = donViTinh;
            NhaCungCap = nhaCungCap;
            MaVach = maVach;
            DinhMuc = dinhMuc;
            SoLuong = soLuong;
            TrangThaiBan = trangThaiBan;
            VAT = vAT;
        }

        public string MaHH { get; set; }
        public string TenHang { get; set; }
        public string MaNH { get; set; }
        public string XuatXu { get; set; }
        public int GiaNhap { get; set; }
        public int GiaBan { get; set; }
        public string DonViTinh { get; set; }
        public string NhaCungCap { get; set; }
        public string MaVach { get; set; }
        public int DinhMuc { get; set; }
        public int SoLuong { get; set; }
        public bool TrangThaiBan { get; set; }
        public int VAT { get; set; }
    }
}
