//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QLSieuThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string SoHD { get; set; }
        public string MaNV { get; set; }
        public string NgayLap { get; set; }
        public string MaKH { get; set; }
        public int  VAT { get; set; }
        public int  TienKhachDua { get; set; }
        public int TienGuiKhach { get; set; }
        public int TongTienKM { get; set; }
        public int ThanhTien { get; set; }

        public HoaDon()
        {
        }

        public HoaDon(string soHD, string maNV, string ngayLap, string maKH, int vAT, int tienKhachDua, int tienGuiKhach, int tongTienKM, int thanhTien)
        {
            SoHD = soHD;
            MaNV = maNV;
            NgayLap = ngayLap;
            MaKH = maKH;
            VAT = vAT;
            TienKhachDua = tienKhachDua;
            TienGuiKhach = tienGuiKhach;
            TongTienKM = tongTienKM;
            ThanhTien = thanhTien;
        }
    }
}
