//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QLSieuThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonCT
    {
        public string SoHD { get; set; }
        public string MaHH { get; set; }
        public int Soluong { get; set; }
        public int DonGia { get; set; }
        public int ThanhTien { get; set; }
        public int VAT { get; set; }
        public string MaKM { get; set; }

        public HoaDonCT(string soHD, string maHH, int soluong, int donGia, int thanhTien, int vAT)
        {
            SoHD = soHD;
            MaHH = maHH;
            Soluong = soluong;
            DonGia = donGia;
            ThanhTien = thanhTien;
            VAT = vAT;
        }
    }
}
