//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QLSieuThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string CMND { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public int Diem { get; set; }
        public string MaMucHang { get; set; }
        public string NgayTao { get; set; }
        public int NamGanBo { get; set; }

        public KhachHang(string maKH, string tenKH, string cMND, string diaChi, string sDT, int diem, string maMucHang, string ngayTao, int namGanBo)
        {
            MaKH = maKH;
            TenKH = tenKH;
            CMND = cMND;
            DiaChi = diaChi;
            SDT = sDT;
            Diem = diem;
            MaMucHang = maMucHang;
            NgayTao = ngayTao;
            NamGanBo = namGanBo;
        }

        public KhachHang()
        {
        }
    }
}
