//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QLSieuThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public string MaKM { get; set; }
        public string MaLyDo { get; set; }
        public string NgayBatDau { get; set; }
        public string NgayKetThuc { get; set; }
        public string NgayTao { get; set; }
        public string MaHH { get; set; }
        public string MaNV { get; set; }
    
        public virtual DSKhuyenMai DSKhuyenMai { get; set; }
    }
}
