//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QLSieuThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien(string maNV, string tenNV, bool gioiTinh, string ngaySinh, string sDT, string diaChi, string email, string userName, string password, string maQuyen, string ngayVaoLam, string ngayNghiViec, bool trangThaiTaiKhoan, int luong, string maCong)
        {
            MaNV = maNV;
            TenNV = tenNV;
            GioiTinh = gioiTinh;
            NgaySinh = ngaySinh;
            SDT = sDT;
            DiaChi = diaChi;
            Email = email;
            UserName = userName;
            Password = password;
            MaQuyen = maQuyen;
            NgayVaoLam = ngayVaoLam;
            NgayNghiViec = ngayNghiViec;
            TrangThaiTaiKhoan = trangThaiTaiKhoan;
            Luong = luong;
            MaCong = maCong;
        }

        public NhanVien(string maNV, string tenNV, bool gioiTinh, string ngaySinh, string sDT, string diaChi, string email, string userName, string password, string maQuyen, string ngayVaoLam, string ngayNghiViec, bool trangThaiTaiKhoan, int luong)
        {
            MaNV = maNV;
            TenNV = tenNV;
            GioiTinh = gioiTinh;
            NgaySinh = ngaySinh;
            SDT = sDT;
            DiaChi = diaChi;
            Email = email;
            UserName = userName;
            Password = password;
            MaQuyen = maQuyen;
            NgayVaoLam = ngayVaoLam;
            NgayNghiViec = ngayNghiViec;
            TrangThaiTaiKhoan = trangThaiTaiKhoan;
            Luong = luong;
        }

        public NhanVien()
        {
        }

        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public bool GioiTinh { get; set; }
        public string NgaySinh { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string MaQuyen { get; set; }
        public string NgayVaoLam { get; set; }
        public string NgayNghiViec { get; set; }
        public bool TrangThaiTaiKhoan { get; set; }
        public int Luong { get; set; }
        public string MaCong { get; set; }
    }
}
