//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QLSieuThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTraHang
    {
        public PhieuTraHang() { }
        public PhieuTraHang(string soPhieuTra, string maNV, DateTime ngayTao, int thanhTien)
        {
            SoPhieuTra = soPhieuTra;
            MaNV = maNV;
            NgayTao = ngayTao;
            ThanhTien = thanhTien;
        }

        public string SoPhieuTra { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayTao { get; set; }
        public int ThanhTien { get; set; }
    }
}
