//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QLSieuThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapHangCT
    {
        public string MaHangNhap { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<int> VAT { get; set; }
    }
}
