//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QLSieuThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapHangCT
    {
        public PhieuNhapHangCT(string maHangNhap, string soPhieu, int soLuongNhap, int vAT)
        {
            MaHangNhap = maHangNhap;
            SoPhieu = soPhieu;
            SoLuongNhap = soLuongNhap;
            VAT = vAT;
        }
        public PhieuNhapHangCT() { }
        public string MaHangNhap { get; set; }
        public string SoPhieu { get; set; }
        public int SoLuongNhap { get; set; }
        public int VAT { get; set; }
    }
}
