//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QLSieuThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTraHangCT
    {
        public PhieuTraHangCT() { }
        public PhieuTraHangCT(string maHangTra, string soPhieuTra, int? soLuongTra, string lydotrahang)
        {
            MaHangTra = maHangTra;
            SoPhieuTra = soPhieuTra;
            SoLuongTra = soLuongTra;
            this.lydotrahang = lydotrahang;
        }

        public string MaHangTra { get; set; }
        public string SoPhieuTra { get; set; }
        public Nullable<int> SoLuongTra { get; set; }
        public string lydotrahang { get; set; }
    }
}
