//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_QLSieuThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapHang
    {
        public PhieuNhapHang()
        {
        }

        public PhieuNhapHang(string soPhieu, string maNV, DateTime ngayTao, string nhaCungCap)
        {
            SoPhieu = soPhieu;
            MaNV = maNV;
            NgayTao = ngayTao;
            NhaCungCap = nhaCungCap;
        }

        public string SoPhieu { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string NhaCungCap { get; set; }
    }
}
